import Head from 'next/head'
import Glogin from './login/Glogin'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Soliq.uz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="key words" content="soliqdan ro'yxatdan o'tish, soliq haqida, ssoliq turali" />
        <link rel="icon" href="https://www.advantour.com/img/uzbekistan/symbolics/gerb_big.jpg" />
      </Head>

      <main>
        <Glogin />

      </main>


    </div>
  )
}
